Karuna1630/JobApplicationTracker

- Frontend/package.json
- Frontend/src/App.jsx
- Frontend/src/Pages/LoginC.jsx
- Frontend/src/Pages/MessagesInbox.jsx
- Frontend/yarn.lock
I have created MessagesInbox page.
> MessagesInbox page

- Frontend/package.json
- Frontend/src/App.jsx
- Frontend/src/Pages/JobPost.jsx
- Frontend/src/Pages/Login.jsx
- Frontend/src/Pages/Register.jsx
- Frontend/yarn.lock
I worked on the JobPost page and fixed the Login and Register pages.
> Create the JobPost page and fix the Login and Register pages

- Frontend/package.json
- Frontend/src/Pages/EditProfile.jsx
- Frontend/yarn.lock
this is the final page of edit user and this allows users to edit their profile information, including name, email, phone, job title, location, and bio. It also supports uploading/removing a profile picture. Styled with Tailwind CSS.
> Final user edit profile

- Frontend/src/App.jsx
- Frontend/src/Pages/JobPost.jsx
- Frontend/src/Pages/JobRecommendation.jsx
- Frontend/src/Pages/Login.jsx
- Frontend/src/Pages/Skill.jsx
> Fixing Login page

- Frontend/src/App.jsx
- Frontend/src/Pages/CompanyProfile.jsx
- Frontend/src/Pages/CompanyR1.jsx
- Frontend/yarn.lock
> Updatecompany profile

- Frontend/src/App.jsx
- Frontend/src/Pages/CompanyProfile.jsx
- Frontend/src/Pages/CompanyR1.jsx
- Frontend/yarn.lock
creating  company profile page
> creating company profil page

- Frontend/package.json
- Frontend/src/Pages/CompanyR1.jsx
- Frontend/yarn.lock
> fixing the company R1

- Frontend/package.json
- Frontend/src/App.jsx
- Frontend/src/Pages/AdminCompany.jsx
- Frontend/yarn.lock
> Add AdminCompany component with dashboard and company panel

- Frontend/package.json
- Frontend/src/Pages/ManageJobs.jsx
- Frontend/yarn.lock
i have created the managejob page
> Creating managejob page

- Frontend/src/Pages/Jobs.jsx
- Frontend/src/Pages/PostJob.jsx
adding the status of jobs that is active or inactive with date valid
> adding the status of jobs that is active or inactive with date valid

- Frontend/src/Components/SidebarMenu.jsx
- Frontend/src/Pages/CompanyInsight.jsx
- Frontend/src/Pages/CompanyProfile.jsx
- Frontend/src/Pages/Jobs.jsx
> removing all the modal

- Frontend/src/Components/SidebarMenu.jsx
- Frontend/src/Pages/ApplicationReceived.jsx
- Frontend/src/Pages/CompanyInsight.jsx
- Frontend/src/Pages/CompanyProfile.jsx
- Frontend/src/Pages/Jobs.jsx
- Frontend/src/Pages/PostJob.jsx
> Sidebarmenu

- Frontend/src/Components/SidebarMenu.jsx
- Frontend/src/Pages/ApplicationReceived.jsx
- Frontend/src/Pages/CompanyInsight.jsx
- Frontend/src/Pages/Jobs.jsx
- Frontend/src/Pages/PostJob.jsx
changing the jobs page into modal
> changing the jobs page into modal

- Frontend/package.json
- Frontend/src/Pages/EditProfile.jsx
- Frontend/yarn.lock
if the jobs is inactive then it delect automatically in the user and company page
> jobs is inactive then it delect automaticaly

- Frontend/src/App.jsx
- Frontend/src/Pages/JobApplicationForm.jsx
> adding application form

- Frontend/src/Components/Experience.jsx
experience data saved in experience table and its id in experiences column of user table
> experience data saved in experience table and its id in user table

- Frontend/package.json
- Frontend/src/Components/Experience.jsx
- Frontend/src/Pages/JobApplicationForm.jsx
- Frontend/yarn.lock
adding experiences in job application form
> adding experiences in job application form

- Frontend/src/Pages/JobApplicationForm.jsx
remove month from job application form
> remove month from job application form

- Frontend/src/Pages/JobApplicationForm.jsx
fixing the job application form
> fixing the job application form

- Frontend/src/App.jsx
- Frontend/src/Pages/ApplicationReceived.jsx
- Frontend/src/Pages/Jobs.jsx
- Frontend/src/Pages/ReviewModal.jsx
> Reviewmodal
